name: Github Actions - Workflow run Triggado
run-name: Running - Workflow run Triggado
on: 
  workflow_run:
    # Escrevemos o NOME do workflow para que ele possa ser triggado
    workflows: [Github Actions - Trigger 1]

jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Workflow que foi Triggado!"